exec: ../dist/build/yesod-datatables-example/yesod-datatables-example
args:
    - production
host: core.feriko.fi

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
copy-to: tero@core.feriko.fi:/opt/keter/incoming
