Default: &defaults
  database: ":memory:"
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: example_test.sqlite3
  <<: *defaults

Staging:
  database: example_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: example_production.sqlite3
  poolsize: 100
  <<: *defaults
